import PDFDocument from "pdfkit"

export async function createPDF(cvData, photoBuffer) {
  return new Promise((resolve, reject) => {
    try {
      const chunks = []
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
      })

      // Collect data chunks
      doc.on("data", (chunk) => chunks.push(chunk))
      doc.on("end", () => resolve(Buffer.concat(chunks)))
      doc.on("error", reject)

      // Add photo
      if (photoBuffer) {
        doc.image(photoBuffer, 50, 50, { width: 100 })
      }

      // Add personal information
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(cvData.personalInfo.name, 170, 50)
        .fontSize(12)
        .font("Helvetica")
        .text(cvData.personalInfo.email, 170, 80)
        .text(cvData.personalInfo.phone, 170, 100)
        .text(cvData.personalInfo.location, 170, 120)

      // Add summary
      doc
        .moveDown(3)
        .fontSize(16)
        .font("Helvetica-Bold")
        .text("PROFESSIONAL SUMMARY", 50, 180)
        .moveDown(0.5)
        .fontSize(12)
        .font("Helvetica")
        .text(cvData.summary, { width: 500 })

      // Add experience
      doc.moveDown(2).fontSize(16).font("Helvetica-Bold").text("WORK EXPERIENCE")

      const yPosition = doc.y
      cvData.experience.forEach((exp) => {
        doc
          .moveDown(0.5)
          .fontSize(14)
          .font("Helvetica-Bold")
          .text(exp.title)
          .fontSize(12)
          .font("Helvetica-Oblique")
          .text(`${exp.company} | ${exp.period}`)
          .font("Helvetica")
          .text(exp.description, { width: 500 })
        doc.moveDown(0.5)
      })

      // Add education
      doc.moveDown(1).fontSize(16).font("Helvetica-Bold").text("EDUCATION")

      cvData.education.forEach((edu) => {
        doc
          .moveDown(0.5)
          .fontSize(14)
          .font("Helvetica-Bold")
          .text(edu.degree)
          .fontSize(12)
          .font("Helvetica")
          .text(`${edu.field}, ${edu.institution}, ${edu.year}`)
        doc.moveDown(0.5)
      })

      // Add skills
      doc
        .moveDown(1)
        .fontSize(16)
        .font("Helvetica-Bold")
        .text("SKILLS")
        .moveDown(0.5)
        .fontSize(12)
        .font("Helvetica")
        .list(cvData.skills, { bulletRadius: 2, textIndent: 20 })

      // Add languages
      doc
        .moveDown(1)
        .fontSize(16)
        .font("Helvetica-Bold")
        .text("LANGUAGES")
        .moveDown(0.5)
        .fontSize(12)
        .font("Helvetica")
        .list(cvData.languages, { bulletRadius: 2, textIndent: 20 })

      // Add footer
      doc.fontSize(10).text("Generated by AI CV Maker Bot", 50, doc.page.height - 50, {
        align: "center",
      })

      doc.end()
    } catch (error) {
      reject(error)
    }
  })
}

